# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end
# create a seed for the clint "default"
# message: Seeding started
puts "Seeding started"

# --------------------------------------------

# destroy all clients
Client.destroy_all

# create a seed for the client "default"
client = Client.find_or_create_by!(name: "default")

# create a seed for the client "HS Ansbach"
Client.find_or_create_by!(name: "HS Ansbach")

# --------------------------------------------

# destroy all users
User.destroy_all

# create a seed for the user "admin"
User.find_or_create_by!(email: "bluemystic48@gmail.com") do |user|
  user.first_name = "admin"
  user.last_name = "admin"
  user.password = "password"
  user.password_confirmation = "password"
  user.role = "admin"
  user.client_id = client.id
end

# create a seed for the user "manager"
User.find_or_create_by!(email: "florian.sitte@live.de") do |user|
  user.first_name = "Florian"
  user.last_name = "Sitte"
  user.password = "password"
  user.password_confirmation = "password"
  user.role = "manager"
  user.client_id = client.id
end

# create a seed for the user "employee"
User.find_or_create_by!(email: "bluemystic48@gmail.com") do |user|
  user.first_name = "Em"
  user.last_name = "Ployee"
  user.password = "password"
  user.password_confirmation = "password"
  user.role = "employee"
  user.client_id = client.id
end

# --------------------------------------------

# destroy all cards
Card.destroy_all

# create seeds for the cards

Card.create!(categorygerman: "fachlich", categoryenglish: "professional", positive: 1, namegerman: "aufbauend kritisch", nameenglish: "constructive critical", groupgerman: "Kritisches Denken", groupenglish: "Critical Thinking", explanationgerman: "Diese Art von Kritik zielt darauf ab, Verbesserungen anzuregen, anstatt zu verletzen. Sie konzentriert sich auf konkrete Aspekte und bietet konstruktive Vorschläge. Beispiel 1: Dein Vortrag war gut, aber du könntest die Einleitung kürzen und mehr visuelle Hilfsmittel verwenden. Beispiel 2: Der Entwurf ist solide, aber eine Überarbeitung des Layouts könnte die Lesbarkeit verbessern.", explanationenglish: "Offers criticism aimed at improvement, rather than solely to find fault. It focuses on specific aspects and suggests solutions. Example 1: The presentation was good, but shortening the introduction and adding visuals would improve it. Example 2: The draft is solid, but revising the layout would enhance readability.", client_id: client.id)
Card.create!(categorygerman: "fachlich", categoryenglish: "professional", positive: 1, namegerman: "detailliert", nameenglish: "detailed", groupgerman: "Kritisches Denken", groupenglish: "Critical Thinking", explanationgerman: "Beschreibt etwas sehr genau und umfassend, mit vielen Einzelheiten. Beispiel 1: Eine detaillierte Beschreibung eines Verbrechens an die Polizei. Beispiel 2: Ein detaillierter Reiseplan für eine mehrtägige Tour.", explanationenglish: "Describes something thoroughly and comprehensively, including many specifics. Example 1: A detailed police report of a crime. Example 2: A detailed itinerary for a multi-day trip.", client_id: client.id)
Card.create!(categorygerman: "fachlich", categoryenglish: "professional", positive: 1, namegerman: "fundiert", nameenglish: "sound standing", groupgerman: "Kritisches Denken", groupenglish: "Critical Thinking", explanationgerman: "Basiert auf soliden Grundlagen, Beweisen und gründlicher Recherche. Beispiel 1: Eine fundierte wissenschaftliche Arbeit mit vielen Quellenangaben. Beispiel 2: Eine fundierte Entscheidung, die auf sorgfältiger Abwägung verschiedener Faktoren beruht.", explanationenglish: "Well-founded, based on solid evidence and thorough research. Example 1: A sound scientific study with many sources cited. Example 2: A sound decision based on careful consideration of various factors.", client_id: client.id)
Card.create!(categorygerman: "fachlich", categoryenglish: "professional", positive: 1, namegerman: "logisch", nameenglish: "logical", groupgerman: "Kritisches Denken", groupenglish: "Critical Thinking", explanationgerman: "Folgt den Regeln der Logik, ist schlüssig und nachvollziehbar. Beispiel 1: Ein logischer Gedankengang, der von Prämisse zu Schlussfolgerung führt. Beispiel 2: Eine logische Argumentation, die auf Fakten und Beweisen beruht.", explanationenglish: "Follows the rules of logic, is coherent and understandable. Example 1: A logical argument that proceeds from premise to conclusion. Example 2: A logical explanation supported by facts and evidence.", client_id: client.id)
Card.create!(categorygerman: "fachlich", categoryenglish: "professional", positive: 1, namegerman: "pragmatisch", nameenglish: "pragmatic", groupgerman: "Praktische Herangehensweise", groupenglish: "Practical Approach", explanationgerman: "Praktisch, realistisch und lösungsorientiert, weniger idealistisch. Beispiel 1: Eine pragmatische Lösung für ein Problem zu finden, anstatt auf eine perfekte, aber unrealistische Lösung zu warten. Beispiel 2: Pragmatisch auf eine veränderte Situation reagieren.", explanationenglish: "Practical, realistic, and solution-oriented, less idealistic. Example 1: Finding a pragmatic solution to a problem, rather than waiting for a perfect, but unrealistic, solution. Example 2: Reacting pragmatically to a change in circumstances.", client_id: client.id)
Card.create!(categorygerman: "fachlich", categoryenglish: "professional", positive: 1, namegerman: "querdenkend", nameenglish: "lateral thinking", groupgerman: "Kreatives Denken", groupenglish: "Creative Thinking", explanationgerman: "Denkt unkonventionell, sucht nach neuen und ungewöhnlichen Lösungsansätzen. Beispiel 1: Eine querdenkende Person findet kreative Lösungen für ein Problem, die andere nicht in Betracht gezogen haben. Beispiel 2: Querdenken im Design.", explanationenglish: "Thinking unconventionally; finding new and unusual approaches to problem-solving. Example 1: A laterally thinking person finds creative solutions that others haven't considered. Example 2: Lateral thinking in design.", client_id: client.id)
Card.create!(categorygerman: "fachlich", categoryenglish: "professional", positive: 1, namegerman: "reflektierend", nameenglish: "reflective", groupgerman: "Selbstreflektion", groupenglish: "Self-Reflection", explanationgerman: "Selbstreflektierend, denkt über das eigene Handeln und dessen Konsequenzen nach. Beispiel 1: Reflektieren über eigene Fehler, um aus ihnen zu lernen. Beispiel 2: Eine reflektierende Betrachtung der eigenen Stärken und Schwächen.", explanationenglish: "Self-reflective; thinking about one's own actions and their consequences. Example 1: Reflecting on past mistakes to learn from them. Example 2: A reflective examination of one's strengths and weaknesses.", client_id: client.id)
Card.create!(categorygerman: "fachlich", categoryenglish: "professional", positive: 1, namegerman: "tiefsinnig", nameenglish: "profound", groupgerman: "Kommunikation", groupenglish: "Communication Skills", explanationgerman: "Tiefgründig, nachdenklich und voller Einsicht. Beispiel 1: Eine tiefsinnige Auseinandersetzung mit einem philosophischen Thema. Beispiel 2: Ein tiefsinniger Roman, der viele Fragen aufwirft.", explanationenglish: "Deep, thoughtful, and insightful. Example 1: A profound engagement with a philosophical topic. Example 2: A profound novel that raises many questions.", client_id: client.id)
Card.create!(categorygerman: "fachlich", categoryenglish: "professional", positive: 1, namegerman: "vorbereitet", nameenglish: "prepared", groupgerman: "Selbstkontrolle", groupenglish: "Self-Control", explanationgerman: "Gut vorbereitet, gut organisiert und bereit für eine bestimmte Aufgabe oder Situation. Beispiel 1: Ein gut vorbereiteter Vortrag mit anschaulichen Beispielen und einer klaren Struktur. Beispiel 2: Eine vorbereitete Reise mit gepacktem Koffer.", explanationenglish: "Well-prepared, well-organized, and ready for a specific task or situation. Example 1: A well-prepared presentation with clear visuals and a strong structure. Example 2: A prepared traveler with a packed suitcase.", client_id: client.id)
Card.create!(categorygerman: "fachlich", categoryenglish: "professional", positive: 1, namegerman: "wortgewandt", nameenglish: "eloquent", groupgerman: "Kommunikation", groupenglish: "Communication Skills", explanationgerman: "Sprachgewandt, eloquent und ausdrucksstark, kann Gedanken und Ideen prägnant und überzeugend formulieren. Beispiel 1: Eine wortgewandte Rede vor einem großen Publikum. Beispiel 2: Ein wortgewandter Autor, der komplexe Themen verständlich aufbereitet.", explanationenglish: "Fluent, articulate, and expressive; able to formulate thoughts and ideas concisely and persuasively. Example 1: An eloquent speech before a large audience. Example 2: An eloquent writer who clarifies complex issues.", client_id: client.id)
Card.create!(categorygerman: "intuitiv", categoryenglish: "intuitive", positive: 1, namegerman: "auf innere Stimme achtend", nameenglish: "listen to one’s inner voice", groupgerman: "Intuitive Wahrnehmung", groupenglish: "Intuitive Awareness", explanationgerman: "Achtsam auf seine Intuition und sein Bauchgefühl; Entscheidungen werden von inneren Impulsen und Gefühlen geleitet. Beispiel 1: Jemanden nicht anstellen, weil man ein ungutes Gefühl hat. Beispiel 2: Ein Projekt spontan abbrechen, da der innere Drang danach besteht.", explanationenglish: "Paying attention to one's intuition and gut feeling; decisions are guided by inner impulses and emotions. Example 1: Not hiring someone because of a bad feeling. Example 2: Spontaneously abandoning a project due to an inner urge.", client_id: client.id)
Card.create!(categorygerman: "intuitiv", categoryenglish: "intuitive", positive: 1, namegerman: "kreativ", nameenglish: "creative", groupgerman: "Kreatives Denken", groupenglish: "Creative Thinking", explanationgerman: "Erfinderisch, fantasievoll und innovativ; fähig, neue Ideen und Lösungen zu entwickeln. Beispiel 1: Ein kreativer Künstler malt ungewöhnliche Bilder. Beispiel 2: Eine kreative Marketingkampagne.", explanationenglish: "Inventive, imaginative, and innovative; able to develop new ideas and solutions. Example 1: A creative artist paints unusual pictures. Example 2: A creative marketing campaign.", client_id: client.id)
Card.create!(categorygerman: "intuitiv", categoryenglish: "intuitive", positive: 1, namegerman: "neugierig", nameenglish: "curious", groupgerman: "Neugier", groupenglish: "Curiosity", explanationgerman: "Wissbegierig, wissendurstig und interessiert an neuen Dingen und Informationen. Beispiel 1: Ein neugieriges Kind stellt viele Fragen. Beispiel 2: Ein neugieriger Wissenschaftler forscht nach neuen Erkenntnissen.", explanationenglish: "Inquisitive, eager to learn, and interested in new things and information. Example 1: A curious child asks many questions. Example 2: A curious scientist researches new discoveries.", client_id: client.id)
Card.create!(categorygerman: "intuitiv", categoryenglish: "intuitive", positive: 1, namegerman: "offen für den Zufall", nameenglish: "open to coincidence", groupgerman: "Neugier", groupenglish: "Curiosity", explanationgerman: "Akzeptiert Ungeplantes und Unerwartetes; lässt sich vom Zufall leiten und ist offen für unvorhergesehene Ereignisse. Beispiel 1: Sich auf eine Reise begeben, ohne den genauen Reiseplan zu kennen. Beispiel 2: Spontan einen neuen Weg einschlagen.", explanationenglish: "Accepting the unplanned and unexpected; allowing oneself to be guided by chance and being open to unforeseen events. Example 1: Embarking on a journey without a detailed itinerary. Example 2: Spontaneously taking a new path.", client_id: client.id)
Card.create!(categorygerman: "intuitiv", categoryenglish: "intuitive", positive: 1, namegerman: "offen für Neues", nameenglish: "open to new Ideas", groupgerman: "Neugier", groupenglish: "Curiosity", explanationgerman: "Aufgeschlossen gegenüber neuen Erfahrungen, Ideen und Perspektiven. Beispiel 1: Eine Person, die gerne neue Kulturen kennenlernt. Beispiel 2: Ein Unternehmen, das neue Technologien einsetzt.", explanationenglish: "Receptive to new experiences, ideas, and perspectives. Example 1: A person who enjoys learning about new cultures. Example 2: A company that adopts new technologies.", client_id: client.id)
Card.create!(categorygerman: "intuitiv", categoryenglish: "intuitive", positive: 1, namegerman: "phantasievoll", nameenglish: "imaginative", groupgerman: "Kreatives Denken", groupenglish: "Creative Thinking", explanationgerman: "Reich an Fantasie und Vorstellungskraft; fähig, sich neue Welten und Szenarien vorzustellen. Beispiel 1: Ein phantasievoller Schriftsteller erschafft einzigartige Geschichten. Beispiel 2: Phantasievolle Kinderzeichnungen.", explanationenglish: "Rich in imagination and fantasy; able to imagine new worlds and scenarios. Example 1: An imaginative writer creates unique stories. Example 2: Imaginative children's drawings.", client_id: client.id)
Card.create!(categorygerman: "intuitiv", categoryenglish: "intuitive", positive: 1, namegerman: "sich inspirieren lassen", nameenglish: "to be inspired by sth.", groupgerman: "Intuitive Wahrnehmung", groupenglish: "Intuitive Awareness", explanationgerman: "Offen für Inspiration von außen; lässt sich von anderen Menschen, Kunst, Natur etc. anregen und beeinflussen. Beispiel 1: Ein Komponist lässt sich von Naturklängen inspirieren. Beispiel 2: Ein Designer lässt sich von Architektur inspirieren.", explanationenglish: "Open to inspiration from outside; allowing oneself to be stimulated and influenced by other people, art, nature, etc. Example 1: A composer is inspired by sounds of nature. Example 2: A designer is inspired by architecture.", client_id: client.id)
Card.create!(categorygerman: "intuitiv", categoryenglish: "intuitive", positive: 1, namegerman: "verspielt", nameenglish: "playful", groupgerman: "Kreatives Denken", groupenglish: "Creative Thinking", explanationgerman: "Spielerisch, unbeschwert und leicht; zeigt eine kindliche Freude und Spontanität. Beispiel 1: Verspielte Interaktionen zwischen Freunden. Beispiel 2: Eine verspielte, bunte Dekoration.", explanationenglish: "Childlike, lighthearted, and spontaneous; showing a playful joy and spontaneity. Example 1: Playful interactions between friends. Example 2: Playful, colorful decoration.", client_id: client.id)
Card.create!(categorygerman: "intuitiv", categoryenglish: "intuitive", positive: 1, namegerman: "vom Herzen geführt", nameenglish: "guided by one’s heart", groupgerman: "Intuitive Wahrnehmung", groupenglish: "Intuitive Awareness", explanationgerman: "Entscheidungen werden von Gefühlen und Überzeugungen geleitet, nicht nur von Vernunft und Logik. Beispiel 1: Eine spontane Spende an eine wohltätige Organisation. Beispiel 2: Sich für eine Sache einsetzen, an die man fest glaubt.", explanationenglish: "Decisions are guided by feelings and convictions, not just by reason and logic. Example 1: A spontaneous donation to a charitable organization. Example 2: Standing up for something one believes in.", client_id: client.id)
Card.create!(categorygerman: "intuitiv", categoryenglish: "intuitive", positive: 1, namegerman: "weltoffen", nameenglish: "cosmopolitan", groupgerman: "Anpassungsfähigkeit", groupenglish: "Adaptability", explanationgerman: "Offen für verschiedene Kulturen, Perspektiven und Menschen; frei von Vorurteilen und Engstirnigkeit. Beispiel 1: Eine weltoffene Familie reist um die Welt. Beispiel 2: Ein weltoffenes Unternehmen beschäftigt Mitarbeiter aus vielen Ländern.", explanationenglish: "Open to different cultures, perspectives, and people; free from prejudices and narrow-mindedness. Example 1: A cosmopolitan family travels the world. Example 2: A cosmopolitan company employs staff from many countries.", client_id: client.id)
Card.create!(categorygerman: "methodisch", categoryenglish: "methodical", positive: 1, namegerman: "entscheidungsfreudig", nameenglish: "decisive", groupgerman: "Entscheidungsfindung", groupenglish: "Decision Making", explanationgerman: "Trifft gerne und schnell Entscheidungen, zögert nicht lange. Beispiel 1: Ein entscheidungsfreudiger Manager trifft schnell wichtige Entscheidungen für sein Unternehmen. Beispiel 2: Ein entscheidungsfreudiger Käufer kauft ein Produkt ohne lange zu überlegen.", explanationenglish: "Makes decisions readily and quickly, doesn't hesitate for long. Example 1: A decisive manager quickly makes important decisions for their company. Example 2: A decisive shopper buys a product without much deliberation.", client_id: client.id)
Card.create!(categorygerman: "methodisch", categoryenglish: "methodical", positive: 1, namegerman: "flexibel", nameenglish: "flexible", groupgerman: "Anpassungsfähigkeit", groupenglish: "Adaptability", explanationgerman: "Anpassungsfähig an verschiedene Situationen und Veränderungen. Beispiel 1: Ein flexibler Arbeitnehmer kann seine Arbeitszeiten an seine Bedürfnisse anpassen. Beispiel 2: Ein flexibles Unternehmen kann sich schnell an Marktveränderungen anpassen.", explanationenglish: "Adaptable to various situations and changes. Example 1: A flexible employee can adjust their work hours to suit their needs. Example 2: A flexible company can quickly adapt to market changes.", client_id: client.id)
Card.create!(categorygerman: "methodisch", categoryenglish: "methodical", positive: 1, namegerman: "führungsstark", nameenglish: "strong leadership", groupgerman: "Entscheidungsfindung", groupenglish: "Decision Making", explanationgerman: "Hat gute Führungsqualitäten, kann andere motivieren und leiten. Beispiel 1: Ein führungsstarker Teamleiter motiviert seine Mitarbeiter zu Höchstleistungen. Beispiel 2: Eine führungstarke Politikerin führt ihre Partei zum Erfolg.", explanationenglish: "Possesses strong leadership qualities, can motivate and guide others. Example 1: A strong leader motivates their team to achieve peak performance. Example 2: A strong leader guides their party to success.", client_id: client.id)
Card.create!(categorygerman: "methodisch", categoryenglish: "methodical", positive: 1, namegerman: "geduldig", nameenglish: "patient", groupgerman: "Entscheidungsfindung", groupenglish: "Decision Making", explanationgerman: "Behält in schwierigen Situationen die Geduld und Ruhe. Beispiel 1: Eine geduldige Lehrerin erklärt ihren Schülern den Stoff immer wieder, bis alle ihn verstanden haben. Beispiel 2: Ein geduldiger Angler wartet stundenlang auf den richtigen Biss.", explanationenglish: "Maintains patience and calm in difficult situations. Example 1: A patient teacher repeatedly explains the material to their students until everyone understands. Example 2: A patient angler waits for hours for the right bite.", client_id: client.id)
Card.create!(categorygerman: "methodisch", categoryenglish: "methodical", positive: 1, namegerman: "mutig vorpreschend", nameenglish: "bravely rush forward", groupgerman: "Entscheidungsfindung", groupenglish: "Decision Making", explanationgerman: "Ist mutig und geht voran, zeigt Initiative und übernimmt Verantwortung. Beispiel 1: Ein mutig vorpreschender Feuerwehrmann rettet Menschen aus brennenden Häusern. Beispiel 2: Eine mutig vorpreschende Unternehmerin gründet ein neues Unternehmen.", explanationenglish: "Is courageous and takes initiative, shows proactiveness, and takes responsibility. Example 1: A firefighter bravely rushes forward to rescue people from burning buildings. Example 2: A brave entrepreneur starts a new business.", client_id: client.id)
Card.create!(categorygerman: "methodisch", categoryenglish: "methodical", positive: 1, namegerman: "optimistisch", nameenglish: "optimistic", groupgerman: "Eigeninitiative", groupenglish: "Personal Initiative", explanationgerman: "Hat eine categoryenglish: "", positive Einstellung und glaubt an den Erfolg. Beispiel 1: Ein optimistischer Mensch sieht auch in schwierigen Situationen Chancen. Beispiel 2: Ein optimistischer Investor glaubt an die Zukunft der Börse.", explanationenglish: "Has a categoryenglish: "", positive attitude and believes in success. Example 1: An optimistic person sees opportunities even in difficult situations. Example 2: An optimistic investor believes in the future of the stock market.", client_id: client.id)
Card.create!(categorygerman: "methodisch", categoryenglish: "methodical", positive: 1, namegerman: "praktisch", nameenglish: "practical", groupgerman: "Praktische Herangehensweise", groupenglish: "Practical Approach", explanationgerman: "Ist pragmatisch und lösungsorientiert, weniger idealistisch. Beispiel 1: Ein praktischer Handwerker findet eine einfache und effektive Lösung für ein Problem. Beispiel 2: Eine praktische Hausfrau organisiert ihren Haushalt effizient.", explanationenglish: "Is pragmatic and solution-oriented, less idealistic. Example 1: A practical handyman finds a simple and effective solution to a problem. Example 2: A practical housewife efficiently manages her household.", client_id: client.id)
Card.create!(categorygerman: "methodisch", categoryenglish: "methodical", positive: 1, namegerman: "strukturiert", nameenglish: "structured", groupgerman: "Zielorientiert", groupenglish: "Goal-Oriented", explanationgerman: "Ordnet und organisiert Dinge systematisch und methodisch. Beispiel 1: Ein strukturierter Student plant sein Studium sorgfältig. Beispiel 2: Ein strukturiertes Unternehmen hat klare Prozesse und Abläufe.", explanationenglish: "Organizes and arranges things systematically and methodically. Example 1: A structured student carefully plans their studies. Example 2: A structured company has clear processes and procedures.", client_id: client.id)
Card.create!(categorygerman: "methodisch", categoryenglish: "methodical", positive: 1, namegerman: "vorausschauend", nameenglish: "foresighted", groupgerman: "Zielorientiert", groupenglish: "Goal-Oriented", explanationgerman: "Denkt vorausschauend und plant im Voraus. Beispiel 1: Ein vorausschauender Investor investiert in zukünftige Trends. Beispiel 2: Ein vorausschauender Politiker plant langfristige Strategien.", explanationenglish: "Thinks ahead and plans in advance. Example 1: A foresighted investor invests in future trends. Example 2: A foresighted politician plans long-term strategies.", client_id: client.id)
Card.create!(categorygerman: "methodisch", categoryenglish: "methodical", positive: 1, namegerman: "zielorientiert", nameenglish: "goal-oriented", groupgerman: "Zielorientiert", groupenglish: "Goal-Oriented", explanationgerman: "Ist zielstrebig und konzentriert sich auf das Erreichen seiner Ziele. Beispiel 1: Ein zielorientierter Sportler trainiert hart, um seine Ziele zu erreichen. Beispiel 2: Ein zielorientierter Mitarbeiter arbeitet effektiv und effizient.", explanationenglish: "Is determined and focused on achieving their goals. Example 1: A goal-oriented athlete trains hard to achieve their goals. Example 2: A goal-oriented employee works effectively and efficiently.", client_id: client.id)
Card.create!(categorygerman: "persönlich", categoryenglish: "personal", positive: 1, namegerman: "ambiguitätstolerant", nameenglish: "ambiguity-tolerant", groupgerman: "Anpassungsfähigkeit", groupenglish: "Adaptability", explanationgerman: "Kann mit Mehrdeutigkeit und Ungenauigkeit umgehen, ohne sich dadurch verunsichern zu lassen. Beispiel 1: Ein Ambiguitätstoleranter Verhandlungspartner kann mit vagen Aussagen umgehen, ohne sofort nach Klarheit zu verlangen. Beispiel 2: Ein Ambiguitätstoleranter Künstler findet Inspiration in offenen, vielschichtigen Situationen.", explanationenglish: "Can handle ambiguity and vagueness without being unsettled. Example 1: An ambiguity-tolerant negotiator can deal with vague statements without immediately demanding clarity. Example 2: An ambiguity-tolerant artist finds inspiration in open, multifaceted situations.", client_id: client.id)
Card.create!(categorygerman: "persönlich", categoryenglish: "personal", positive: 1, namegerman: "demütig", nameenglish: "humble", groupgerman: "Persönliche Entwicklung", groupenglish: "Personal Growth", explanationgerman: "Bescheiden und ohne Überheblichkeit; wertschätzt andere und sich selbst nicht zu hoch ein. Beispiel 1: Ein demütiger Mensch gibt anderen die Ehre für ihre Leistungen. Beispiel 2: Ein demütiger Schüler akzeptiert Kritik und lernt daraus.", explanationenglish: "Modest and without arrogance; values others and doesn't overestimate oneself. Example 1: A humble person gives others credit for their achievements. Example 2: A humble student accepts criticism and learns from it.", client_id: client.id)
Card.create!(categorygerman: "persönlich", categoryenglish: "personal", positive: 1, namegerman: "diszipliniert", nameenglish: "disciplined", groupgerman: "Selbstkontrolle", groupenglish: "Self-Control", explanationgerman: "Selbstdiszipliniert, organisiert und zielstrebig; hält sich an Regeln und Pläne. Beispiel 1: Ein disziplinierter Sportler trainiert regelmäßig und hält sich an seinen Trainingsplan. Beispiel 2: Ein disziplinierter Student bearbeitet seine Hausaufgaben pünktlich und gewissenhaft.", explanationenglish: "Self-disciplined, organized, and determined; adheres to rules and plans. Example 1: A disciplined athlete trains regularly and adheres to their training plan. Example 2: A disciplined student completes their homework punctually and conscientiously.", client_id: client.id)
Card.create!(categorygerman: "persönlich", categoryenglish: "personal", positive: 1, namegerman: "enthusiastisch", nameenglish: "enthusiastic", groupgerman: "Eigeninitiative", groupenglish: "Personal Initiative", explanationgerman: "Begeistert und mit viel Leidenschaft bei der Sache. Beispiel 1: Ein enthusiastischer Lehrer begeistert seine Schüler für sein Fach. Beispiel 2: Ein enthusiastischer Musiker spielt mit vollem Herzen.", explanationenglish: "Passionate and eager; showing great excitement and energy. Example 1: An enthusiastic teacher inspires their students to love their subject. Example 2: An enthusiastic musician plays with their whole heart.", client_id: client.id)
Card.create!(categorygerman: "persönlich", categoryenglish: "personal", positive: 1, namegerman: "selbstironisch", nameenglish: "self-ironic", groupgerman: "Selbstreflektion", groupenglish: "Self-Reflection", explanationgerman: "Kann über sich selbst lachen und seine Fehler mit Humor sehen. Beispiel 1: Ein selbstironischer Mensch macht sich über seine eigenen Missgeschicke lustig. Beispiel 2: Ein selbstironischer Redner kann sich über seine eigenen Versprecher amüsieren.", explanationenglish: "Can laugh at themselves and see their mistakes with humor. Example 1: A self-ironic person makes fun of their own mishaps. Example 2: A self-ironic speaker can laugh about their own slips of the tongue.", client_id: client.id)
Card.create!(categorygerman: "persönlich", categoryenglish: "personal", positive: 1, namegerman: "selbstmotiviert", nameenglish: "self-motivated", groupgerman: "Eigeninitiative", groupenglish: "Personal Initiative", explanationgerman: "Motiviert sich selbst und braucht keine ständige Aufforderung von außen. Beispiel 1: Ein selbstmotivierter Mitarbeiter arbeitet auch ohne ständige Kontrolle effizient. Beispiel 2: Ein selbstmotivierter Student setzt sich selbstständig Lernziele und erreicht sie.", explanationenglish: "Motivates themselves and doesn't need constant external encouragement. Example 1: A self-motivated employee works efficiently even without constant supervision. Example 2: A self-motivated student sets their own learning goals and achieves them.", client_id: client.id)
Card.create!(categorygerman: "persönlich", categoryenglish: "personal", positive: 1, namegerman: "selbstreflektiert", nameenglish: "self-reflective", groupgerman: "Selbstreflektion", groupenglish: "Self-Reflection", explanationgerman: "Denkt über sich selbst und sein Handeln nach, analysiert seine Stärken und Schwächen. Beispiel 1: Ein selbstreflektierter Mensch lernt aus seinen Fehlern und verbessert sich stetig. Beispiel 2: Ein selbstreflektierter Manager hinterfragt regelmäßig seine Entscheidungen.", explanationenglish: "Thinks about themselves and their actions, analyzes their strengths and weaknesses. Example 1: A self-reflective person learns from their mistakes and constantly improves. Example 2: A self-reflective manager regularly questions their decisions.", client_id: client.id)
Card.create!(categorygerman: "persönlich", categoryenglish: "personal", positive: 1, namegerman: "sinnfindend", nameenglish: "find the meaning of sth.", groupgerman: "Persönliche Entwicklung", groupenglish: "Personal Growth", explanationgerman: "Ist auf der Suche nach Sinn und Bedeutung im Leben. Beispiel 1: Ein sinnfindender Mensch engagiert sich ehrenamtlich, um etwas zum Guten zu bewegen. Beispiel 2: Ein sinnfindender Mensch reflektiert seine Lebensziele regelmäßig.", explanationenglish: "Seeks meaning and purpose in life or a situation. Example 1: A person who finds meaning engages in volunteer work to make a categoryenglish: "", positive impact. Example 2: A person who finds meaning regularly reflects on their life goals.", client_id: client.id)
Card.create!(categorygerman: "persönlich", categoryenglish: "personal", positive: 1, namegerman: "über sich hinauswachsen", nameenglish: "to grow beyond oneself", groupgerman: "Persönliche Entwicklung", groupenglish: "Personal Growth", explanationgerman: "Entwickelt sich persönlich weiter und überwindet seine Grenzen. Beispiel 1: Ein Mensch, der über sich hinauswächst, lernt eine neue Sprache oder meistert eine große Herausforderung. Beispiel 2: Jemand, der über sich hinauswächst, startet ein eigenes Unternehmen trotz anfänglicher Zweifel.", explanationenglish: "Develops personally and overcomes their limitations. Example 1: Someone who grows beyond themselves learns a new language or masters a great challenge. Example 2: Someone who grows beyond themselves starts their own business despite initial doubts.", client_id: client.id)
Card.create!(categorygerman: "persönlich", categoryenglish: "personal", positive: 1, namegerman: "zuverlässig", nameenglish: "reliable", groupgerman: "Selbstkontrolle", groupenglish: "Self-Control", explanationgerman: "Verlässlich und vertrauenswürdig; hält Versprechen und Termine ein. Beispiel 1: Ein zuverlässiger Mitarbeiter ist immer pünktlich und erledigt seine Aufgaben sorgfältig. Beispiel 2: Ein zuverlässiger Freund ist immer für einen da, wenn man ihn braucht.", explanationenglish: "Dependable and trustworthy; keeps promises and meets deadlines. Example 1: A reliable employee is always punctual and completes their tasks carefully. Example 2: A reliable friend is always there when you need them.", client_id: client.id)
Card.create!(categorygerman: "sozial", categoryenglish: "social", positive: 1, namegerman: "einfühlsam", nameenglish: "sensitive", groupgerman: "Empathie", groupenglish: "Empathetic Traits", explanationgerman: "Kann die Gefühle anderer verstehen und nachvollziehen. Beispiel 1: Eine einfühlsame Person tröstet einen Freund in seiner Trauer. Beispiel 2: Ein einfühlsamer Lehrer versteht die Probleme seiner Schüler.", explanationenglish: "Empathetic; able to understand and share the feelings of others. Example 1: A sensitive person comforts a friend in their grief. Example 2: A sensitive teacher understands the problems of their students.", client_id: client.id)
Card.create!(categorygerman: "sozial", categoryenglish: "social", positive: 1, namegerman: "gerecht", nameenglish: "fair", groupgerman: "Fairness", groupenglish: "Fairness", explanationgerman: "Fair, unparteiisch und objektiv; handelt nach Gerechtigkeitsprinzipien. Beispiel 1: Ein gerechter Richter fällt ein unparteiisches Urteil. Beispiel 2: Eine gerechte Verteilung von Ressourcen.", explanationenglish: "Impartial and objective; acts according to principles of justice. Example 1: A fair judge makes an unbiased judgment. Example 2: A fair distribution of resources.", client_id: client.id)
Card.create!(categorygerman: "sozial", categoryenglish: "social", positive: 1, namegerman: "hilfsbereit", nameenglish: "helpful", groupgerman: "Unterstützende Merkmale", groupenglish: "Supportive Traits", explanationgerman: "Steht anderen gerne mit Rat und Tat zur Seite. Beispiel 1: Ein hilfsbereiter Nachbar hilft einer alten Dame beim Einkaufen. Beispiel 2: Ein hilfsbereiter Kollege unterstützt seine Kollegen bei der Arbeit.", explanationenglish: "Willing to give assistance; ready to help. Example 1: A helpful neighbor assists an elderly lady with grocery shopping. Example 2: A helpful colleague supports their coworkers at work.", client_id: client.id)
Card.create!(categorygerman: "sozial", categoryenglish: "social", positive: 1, namegerman: "kontaktfreudig", nameenglish: "sociable", groupgerman: "Soziales Engagement", groupenglish: "Social Engagement", explanationgerman: "Ist gesellig und sucht gerne den Kontakt zu anderen Menschen. Beispiel 1: Eine kontaktfreudige Person geht gerne auf Menschen zu. Beispiel 2: Eine kontaktfreudige Person hat viele Freunde.", explanationenglish: "Outgoing and friendly; enjoys interacting with others. Example 1: A sociable person easily approaches others. Example 2: A sociable person has many friends.", client_id: client.id)
Card.create!(categorygerman: "sozial", categoryenglish: "social", positive: 1, namegerman: "respektvoll", nameenglish: "respectful", groupgerman: "Empathie", groupenglish: "Empathetic Traits", explanationgerman: "Behandelt andere mit Respekt und Wertschätzung. Beispiel 1: Ein respektvoller Schüler behandelt seine Lehrer mit Achtung. Beispiel 2: Ein respektvoller Umgang miteinander.", explanationenglish: "Treats others with respect and consideration. Example 1: A respectful student treats their teachers with respect. Example 2: Respectful interaction with each other.", client_id: client.id)
Card.create!(categorygerman: "sozial", categoryenglish: "social", positive: 1, namegerman: "rücksichtsvoll", nameenglish: "considerate", groupgerman: "Empathie", groupenglish: "Empathetic Traits", explanationgerman: "Berücksichtigt die Bedürfnisse und Gefühle anderer Menschen. Beispiel 1: Ein rücksichtsvoller Autofahrer fährt langsam in Wohngebieten. Beispiel 2: Ein rücksichtsvoller Kollege stört seine Kollegen nicht unnötig.", explanationenglish: "Thoughtful and takes the needs and feelings of others into account. Example 1: A considerate driver drives slowly in residential areas. Example 2: A considerate colleague doesn't unnecessarily disturb their colleagues.", client_id: client.id)
Card.create!(categorygerman: "sozial", categoryenglish: "social", positive: 1, namegerman: "tolerant", nameenglish: "tolerant", groupgerman: "Fairness", groupenglish: "Fairness", explanationgerman: "Akzeptiert andere Meinungen und Lebensweisen, auch wenn sie von den eigenen abweichen. Beispiel 1: Eine tolerante Gesellschaft akzeptiert Menschen verschiedener Kulturen. Beispiel 2: Ein toleranter Chef akzeptiert die Schwächen seiner Mitarbeiter.", explanationenglish: "Accepting of other opinions and ways of life, even if they differ from one's own. Example 1: A tolerant society accepts people of different cultures. Example 2: A tolerant boss accepts the weaknesses of their employees.", client_id: client.id)
Card.create!(categorygerman: "sozial", categoryenglish: "social", positive: 1, namegerman: "unterstützend", nameenglish: "supportive", groupgerman: "Unterstützende Merkmale", groupenglish: "Supportive Traits", explanationgerman: "Bietet Hilfe und Unterstützung an, um anderen zu helfen. Beispiel 1: Ein unterstützender Freund hilft seinem Freund bei seinen Problemen. Beispiel 2: Ein unterstützender Partner hilft seinem Partner beim Erreichen seiner Ziele.", explanationenglish: "Providing help and assistance to others. Example 1: A supportive friend helps their friend with their problems. Example 2: A supportive partner helps their partner achieve their goals.", client_id: client.id)
Card.create!(categorygerman: "sozial", categoryenglish: "social", positive: 1, namegerman: "vertrauensvoll", nameenglish: "trustful", groupgerman: "Soziales Engagement", groupenglish: "Social Engagement", explanationgerman: "Ist vertrauenswürdig und ehrlich; man kann sich auf ihn verlassen. Beispiel 1: Ein vertrauensvoller Freund bewahrt Geheimnisse. Beispiel 2: Ein vertrauensvoller Partner ist ehrlich und offen.", explanationenglish: "Worthy of trust; dependable and honest. Example 1: A trustworthy friend keeps secrets. Example 2: A trustworthy partner is honest and open.", client_id: client.id)
Card.create!(categorygerman: "sozial", categoryenglish: "social", positive: 1, namegerman: "warmherzig", nameenglish: "warm-hearted", groupgerman: "Empathie", groupenglish: "Empathetic Traits", explanationgerman: "Herzlich, freundlich und mitfühlend; zeigt Wärme und Zuneigung. Beispiel 1: Eine warmherzige Person empfängt ihre Gäste freundlich. Beispiel 2: Eine warmherzige Umarmung.", explanationenglish: "Kind, friendly, and compassionate; shows warmth and affection. Example 1: A warm-hearted person welcomes their guests warmly. Example 2: A warm embrace.", client_id: client.id)

Card.create!(categorygerman: "fachlich", categoryenglish: "professional", positive: 0, namegerman: "nicht fundiert", nameenglish: "not founded", groupgerman: "Mangel an Grundlagen", groupenglish: "Lack of Foundation", explanationgerman: "Nicht gut begründet, oberflächlich oder spekulativ. Beispiel 1: Eine nicht fundierte Behauptung ohne Belege. Beispiel 2: Eine nicht fundierte Kritik ohne konkrete Beispiele.", explanationenglish: "Not well-founded, lacking solid evidence or basis. Example 1: An unfounded claim without supporting evidence. Example 2: Unfounded criticism lacking concrete examples.", client_id: client.id)
Card.create!(categorygerman: "fachlich", categoryenglish: "professional", positive: 0, namegerman: "oberflächlich", nameenglish: "superficial", groupgerman: "Mangel an Tiefe", groupenglish: "Lack of Depth", explanationgerman: "Nur an der Oberfläche bleibend, ohne Tiefe oder Detailgenauigkeit. Beispiel 1: Eine oberflächliche Analyse eines Problems. Beispiel 2: Ein oberflächliches Verständnis eines Themas.", explanationenglish: "Shallow, lacking depth or detail. Example 1: A superficial analysis of a problem. Example 2: A superficial understanding of a topic.", client_id: client.id)
Card.create!(categorygerman: "fachlich", categoryenglish: "professional", positive: 0, namegerman: "pauschalisierend", nameenglish: "generalizing", groupgerman: "Mangel an Tiefe", groupenglish: "Lack of Depth", explanationgerman: "Verallgemeinernd, ohne Nuancen oder Ausnahmen. Beispiel 1: Pauschalisierende Aussagen über eine ganze Gruppe von Menschen. Beispiel 2: Eine pauschalisierende Beurteilung einer Situation.", explanationenglish: "Making broad statements without considering nuances or exceptions. Example 1: Generalizing statements about an entire group of people. Example 2: A generalizing assessment of a situation.", client_id: client.id)
Card.create!(categorygerman: "fachlich", categoryenglish: "professional", positive: 0, namegerman: "sich anpassend", nameenglish: "adaptive", groupgerman: "Fairnessprobleme", groupenglish: "Fairness Issues", explanationgerman: "Anpassungsfähig an verschiedene Situationen und Umgebungen. Beispiel 1: Ein sich anpassender Mitarbeiter kann sich schnell auf neue Aufgaben einstellen. Beispiel 2: Eine sich anpassende Pflanze gedeiht in verschiedenen Klimazonen.", explanationenglish: "Able to adjust to different situations and environments. Example 1: An adaptable employee can quickly adjust to new tasks. Example 2: An adaptive plant thrives in various climates.", client_id: client.id)
Card.create!(categorygerman: "fachlich", categoryenglish: "professional", positive: 0, namegerman: "unlogisch", nameenglish: "illogical", groupgerman: "Mangel an Tiefe", groupenglish: "Lack of Depth", explanationgerman: "Widersprüchlich, nicht nachvollziehbar oder irrational. Beispiel 1: Ein unlogischer Gedankengang. Beispiel 2: Ein unlogischer Schluss.", explanationenglish: "Contradictory, unreasonable, or irrational. Example 1: An illogical line of reasoning. Example 2: An illogical conclusion.", client_id: client.id)
Card.create!(categorygerman: "fachlich", categoryenglish: "professional", positive: 0, namegerman: "unreflektiert", nameenglish: "unreflected", groupgerman: "Mangel an Tiefe", groupenglish: "Lack of Depth", explanationgerman: "Ohne Selbstreflexion oder kritische Betrachtung. Beispiel 1: Eine unreflektierte Aussage ohne Hinterfragung. Beispiel 2: Unreflektiertes Handeln ohne Konsequenzen abzuwägen.", explanationenglish: "Without self-reflection or critical consideration. Example 1: An unreflected statement without questioning. Example 2: Unreflected actions without weighing consequences.", client_id: client.id)
Card.create!(categorygerman: "fachlich", categoryenglish: "professional", positive: 0, namegerman: "unvorbereitet", nameenglish: "unprepared", groupgerman: "Mangel an Grundlagen", groupenglish: "Lack of Foundation", explanationgerman: "Nicht vorbereitet, ohne Planung oder Vorbereitung. Beispiel 1: Ein unvorbereiteter Vortrag ohne Struktur. Beispiel 2: Ein unvorbereiteter Schüler ohne Hausaufgaben.", explanationenglish: "Not prepared, lacking planning or prior arrangements. Example 1: An unprepared presentation lacking structure. Example 2: An unprepared student without homework.", client_id: client.id)
Card.create!(categorygerman: "fachlich", categoryenglish: "professional", positive: 0, namegerman: "wortkarg", nameenglish: "taciturn", groupgerman: "Mangel an Engagement", groupenglish: "Lack of Engagement", explanationgerman: "Sprachkarg, wenig sprechend oder wortarm. Beispiel 1: Ein wortkarger Mensch antwortet nur kurz und knapp. Beispiel 2: Ein wortkarger Bericht ohne viele Details.", explanationenglish: "Reserved or uncommunicative in speech; saying little. Example 1: A taciturn person only answers briefly and concisely. Example 2: A taciturn report without many details.", client_id: client.id)
Card.create!(categorygerman: "fachlich", categoryenglish: "professional", positive: 0, namegerman: "zerstörerisch kritisch", nameenglish: "destructive critical", groupgerman: "Kontrollprobleme", groupenglish: "Control Issues", explanationgerman: "Kritik, die eher verletzt und demoliert als konstruktiv ist. Beispiel 1: Zerstörerische Kritik ohne Lösungsvorschläge. Beispiel 2: Zerstörerische Kritik, die die Motivation untergräbt.", explanationenglish: "Criticism that is hurtful and damaging rather than constructive. Example 1: Destructive criticism without offering solutions. Example 2: Destructive criticism that undermines motivation.", client_id: client.id)
Card.create!(categorygerman: "fachlich", categoryenglish: "professional", positive: 0, namegerman: "zu perfektionistisch", nameenglish: "too perfectionistic", groupgerman: "Kontrollprobleme", groupenglish: "Control Issues", explanationgerman: "Übertriebener Perfektionismus, der lähmend wirken kann. Beispiel 1: Ein zu perfektionistischer Mensch kann ein Projekt nicht abschließen, weil es nie perfekt genug ist. Beispiel 2: Zu perfektionistische Detailarbeit.", explanationenglish: "Excessive perfectionism that can be paralyzing. Example 1: An overly perfectionistic person cannot complete a project because it's never perfect enough. Example 2: Overly perfectionistic attention to detail.", client_id: client.id)
Card.create!(categorygerman: "intuitiv", categoryenglish: "intuitive", positive: 0, namegerman: "auf äußere Meinung achtend", nameenglish: "third party-directed", groupgerman: "Führungsprobleme", groupenglish: "Leadership Issues", explanationgerman: "Stark von der Meinung anderer beeinflusst; lässt sich leicht von außen leiten. Beispiel 1: Ein auf äußere Meinung achtender Mensch kauft ein Produkt, weil es alle anderen auch haben. Beispiel 2: Eine auf äußere Meinung achtender Student wählt ein Fach, weil es angeblich gute Jobaussichten bietet.", explanationenglish: "Heavily influenced by the opinions of others; easily swayed by external factors. Example 1: A person heavily influenced by outside opinions buys a product because everyone else has it. Example 2: A student chooses a major based on perceived job prospects.", client_id: client.id)
Card.create!(categorygerman: "intuitiv", categoryenglish: "intuitive", positive: 0, namegerman: "interessenlos", nameenglish: "without interest", groupgerman: "Mangel an Engagement", groupenglish: "Lack of Engagement", explanationgerman: "Zeigt kein Interesse oder Engagement. Beispiel 1: Ein interessenloser Schüler hört im Unterricht nicht zu. Beispiel 2: Ein interessenloser Mitarbeiter erfüllt seine Aufgaben nur widerwillig.", explanationenglish: "Shows no interest or engagement. Example 1: An uninterested student doesn't listen in class. Example 2: An uninterested employee only reluctantly completes their tasks.", client_id: client.id)
Card.create!(categorygerman: "intuitiv", categoryenglish: "intuitive", positive: 0, namegerman: "phantasielos", nameenglish: "unimaginative", groupgerman: "Mangel an Kreativität", groupenglish: "Lack of Creativity", explanationgerman: "Fantasielos, ohne Vorstellungskraft oder Kreativität. Beispiel 1: Ein phantasieloser Schriftsteller schreibt langweilige Geschichten. Beispiel 2: Ein phantasieloser Zeichner kann nur einfache Motive darstellen.", explanationenglish: "Lacking imagination or creativity. Example 1: An unimaginative writer writes boring stories. Example 2: An unimaginative artist can only depict simple motifs.", client_id: client.id)
Card.create!(categorygerman: "intuitiv", categoryenglish: "intuitive", positive: 0, namegerman: "sich dem Neuen verschließen", nameenglish: "not open to the new ideas", groupgerman: "Veränderungsaversion", groupenglish: "Change Aversion", explanationgerman: "Ist abgeneigt gegenüber neuen Ideen und Erfahrungen; widersetzt sich Veränderungen. Beispiel 1: Eine Person, die sich dem Neuen verschließt, lehnt neue Technologien ab. Beispiel 2: Ein Unternehmen, das sich dem Neuen verschließt, bleibt hinter dem Wettbewerb zurück.", explanationenglish: "Resistant to new ideas and experiences; opposes change. Example 1: A person closed to new ideas rejects new technologies. Example 2: A company that resists innovation falls behind the competition.", client_id: client.id)
Card.create!(categorygerman: "intuitiv", categoryenglish: "intuitive", positive: 0, namegerman: "sich dem Zufall verschließen", nameenglish: "not open to the coincidence", groupgerman: "Veränderungsaversion", groupenglish: "Change Aversion", explanationgerman: "Vermeidet Risiken und Ungewissheiten; plant alles genau und lässt nichts dem Zufall über. Beispiel 1: Eine Person, die sich dem Zufall verschließt, plant jeden Tag detailliert. Beispiel 2: Ein Unternehmen, das sich dem Zufall verschließt, geht kaum Risiken ein.", explanationenglish: "Avoids risks and uncertainties; plans everything precisely and leaves nothing to chance. Example 1: A person closed to coincidence plans every day in detail. Example 2: A company that avoids risks takes few chances.", client_id: client.id)
Card.create!(categorygerman: "intuitiv", categoryenglish: "intuitive", positive: 0, namegerman: "uninspiriert", nameenglish: "uninspired", groupgerman: "Mangel an Kreativität", groupenglish: "Lack of Creativity", explanationgerman: "Unmotiviert, lustlos und ohne kreative Ideen. Beispiel 1: Ein uninspirierter Künstler kann kein neues Werk schaffen. Beispiel 2: Ein uninspirierter Schüler arbeitet ohne Eifer.", explanationenglish: "Unmotivated, listless, and lacking creative ideas. Example 1: An uninspired artist cannot create a new work. Example 2: An uninspired student works without enthusiasm.", client_id: client.id)
Card.create!(categorygerman: "intuitiv", categoryenglish: "intuitive", positive: 0, namegerman: "unkreativ", nameenglish: "uncreative", groupgerman: "Mangel an Kreativität", groupenglish: "Lack of Creativity", explanationgerman: "Fantasielos, einfallslos und nicht erfinderisch. Beispiel 1: Ein unkreativer Koch bereitet immer die gleichen Gerichte zu. Beispiel 2: Ein unkreativer Designer kopiert bestehende Designs.", explanationenglish: "Unimaginative, uninspired, and not inventive. Example 1: An uncreative cook always prepares the same dishes. Example 2: An uncreative designer copies existing designs.", client_id: client.id)
Card.create!(categorygerman: "intuitiv", categoryenglish: "intuitive", positive: 0, namegerman: "verbissen", nameenglish: "doggedly", groupgerman: "Starrheit", groupenglish: "Rigidity", explanationgerman: "Hartnäckig und unnachgiebig, oft auf Kosten anderer. Beispiel 1: Ein verbissener Politiker verfolgt seine Ziele mit allen Mitteln. Beispiel 2: Ein verbissener Sportler gibt trotz Verletzung nicht auf.", explanationenglish: "Stubbornly persistent, often at the expense of others. Example 1: A dogged politician pursues their goals by any means. Example 2: A dogged athlete doesn't give up despite injury.", client_id: client.id)
Card.create!(categorygerman: "intuitiv", categoryenglish: "intuitive", positive: 0, namegerman: "vom Kopf gesteuert", nameenglish: "controlled by one’s head", groupgerman: "Kontrollprobleme", groupenglish: "Control Issues", explanationgerman: "Rational, logisch und verstandesgeleitet; weniger von Gefühlen und Emotionen beeinflusst. Beispiel 1: Eine vom Kopf gesteuerte Entscheidung basiert auf Fakten und Logik. Beispiel 2: Ein vom Kopf gesteuerter Mensch lässt sich nicht von Emotionen leiten.", explanationenglish: "Rational, logical, and intellectually driven; less influenced by feelings and emotions. Example 1: A head-driven decision is based on facts and logic. Example 2: A head-driven person doesn't let emotions guide them.", client_id: client.id)
Card.create!(categorygerman: "intuitiv", categoryenglish: "intuitive", positive: 0, namegerman: "weltfremd", nameenglish: "unworldly", groupgerman: "Praxisfremd", groupenglish: "Lack of Practicality", explanationgerman: "Von der Realität getrennt, naiv und unrealistisch. Beispiel 1: Ein weltfremder Mensch versteht die Probleme der realen Welt nicht. Beispiel 2: Eine weltfremde Idee, die nicht umsetzbar ist.", explanationenglish: "Out of touch with reality; naive and unrealistic. Example 1: An unworldly person doesn't understand the problems of the real world. Example 2: An unworldly idea that is not feasible.", client_id: client.id)
Card.create!(categorygerman: "methodisch", categoryenglish: "methodical", positive: 0, namegerman: "aktionistisch", nameenglish: "actionistic", groupgerman: "Impulsivität", groupenglish: "Impulsivity", explanationgerman: "Handlungsorientiert, tatkräftig, oft ohne viel Planung. Beispiel 1: Ein aktionistischer Aktivist protestiert spontan und direkt. Beispiel 2: Eine aktionistische Marketingkampagne, die schnell auf den Markt gebracht wird.", explanationenglish: "Action-oriented, proactive, often without much planning. Example 1: An actionistic activist protests spontaneously and directly. Example 2: An actionistic marketing campaign quickly launched.", client_id: client.id)
Card.create!(categorygerman: "methodisch", categoryenglish: "methodical", positive: 0, namegerman: "ängstlich abwartend", nameenglish: "awaiting anxiously", groupgerman: "Führungsprobleme", groupenglish: "Leadership Issues", explanationgerman: "Ängstlich, zurückhaltend und passiv; wartet ab, anstatt aktiv zu werden. Beispiel 1: Ein ängstlich abwartender Mensch traut sich nicht, neue Kontakte zu knüpfen. Beispiel 2: Ein ängstlich abwartender Investor wartet auf bessere Marktbedingungen.", explanationenglish: "Anxious, hesitant, and passive; waits instead of taking action. Example 1: An anxiously awaiting person doesn't dare to make new contacts. Example 2: An anxiously awaiting investor waits for better market conditions.", client_id: client.id)
Card.create!(categorygerman: "methodisch", categoryenglish: "methodical", positive: 0, namegerman: "entscheidungsarm", nameenglish: "indecisive", groupgerman: "Führungsprobleme", groupenglish: "Leadership Issues", explanationgerman: "Unschlüssig und unentschlossen; fällt schwer, Entscheidungen zu treffen. Beispiel 1: Ein entscheidungsarmer Mensch kann sich nicht für ein Restaurant entscheiden. Beispiel 2: Ein entscheidungsarmer Manager verzögert wichtige Entscheidungen.", explanationenglish: "Unable to make decisions easily; hesitant. Example 1: An indecisive person can't decide on a restaurant. Example 2: An indecisive manager delays important decisions.", client_id: client.id)
Card.create!(categorygerman: "methodisch", categoryenglish: "methodical", positive: 0, namegerman: "führungsschwach", nameenglish: "weak leadership", groupgerman: "Führungsprobleme", groupenglish: "Leadership Issues", explanationgerman: "Hat schwache Führungsqualitäten; kann andere nicht gut motivieren oder leiten. Beispiel 1: Ein führungsschwacher Vorgesetzter kann seine Mitarbeiter nicht motivieren. Beispiel 2: Eine führungsschwache Führungskraft verliert die Kontrolle über ihr Team.", explanationenglish: "Lacks strong leadership qualities; cannot effectively motivate or guide others. Example 1: A weak leader cannot motivate their employees. Example 2: A weak leader loses control of their team.", client_id: client.id)
Card.create!(categorygerman: "methodisch", categoryenglish: "methodical", positive: 0, namegerman: "pessimistisch", nameenglish: "pessimistic", groupgerman: "Vertrauensprobleme", groupenglish: "Trust Issues", explanationgerman: "Negativ eingestellt und glaubt eher an Misserfolg als an Erfolg. Beispiel 1: Ein pessimistischer Mensch erwartet das Schlimmste. Beispiel 2: Ein pessimistischer Investor glaubt nicht an den Erfolg einer Investition.", explanationenglish: "Negative in outlook and more likely to believe in failure than success. Example 1: A pessimistic person expects the worst. Example 2: A pessimistic investor doesn't believe in the success of an investment.", client_id: client.id)
Card.create!(categorygerman: "methodisch", categoryenglish: "methodical", positive: 0, namegerman: "unflexibel", nameenglish: "inflexible", groupgerman: "Starrheit", groupenglish: "Rigidity", explanationgerman: "Starr, unnachgiebig und nicht anpassungsfähig. Beispiel 1: Ein unflexibler Mensch kann sich nicht an neue Situationen anpassen. Beispiel 2: Ein unflexibles Unternehmen weigert sich, neue Technologien zu verwenden.", explanationenglish: "Rigid, inflexible, and unable to adapt. Example 1: An inflexible person cannot adapt to new situations. Example 2: An inflexible company refuses to use new technologies.", client_id: client.id)
Card.create!(categorygerman: "methodisch", categoryenglish: "methodical", positive: 0, namegerman: "ungeduldig", nameenglish: "impatient", groupgerman: "Impulsivität", groupenglish: "Impulsivity", explanationgerman: "Hat wenig Geduld und ist leicht reizbar. Beispiel 1: Ein ungeduldiger Autofahrer hupt ständig im Stau. Beispiel 2: Ein ungeduldiger Lehrer verliert schnell die Geduld mit seinen Schülern.", explanationenglish: "Lacks patience and is easily irritated. Example 1: An impatient driver constantly honks in traffic. Example 2: An impatient teacher quickly loses patience with their students.", client_id: client.id)
Card.create!(categorygerman: "methodisch", categoryenglish: "methodical", positive: 0, namegerman: "unstrukturiert", nameenglish: "unstructured", groupgerman: "Mangel an Grundlagen", groupenglish: "Lack of Foundation", explanationgerman: "Unorganisiert und chaotisch; ohne System oder Plan. Beispiel 1: Ein unstrukturierter Arbeitsplatz ist voller Unordnung. Beispiel 2: Ein unstrukturierter Essay ist ohne klaren roten Faden.", explanationenglish: "Disorganized and chaotic; lacking system or plan. Example 1: An unstructured workspace is full of clutter. Example 2: An unstructured essay lacks a clear theme.", client_id: client.id)
Card.create!(categorygerman: "methodisch", categoryenglish: "methodical", positive: 0, namegerman: "ziellos", nameenglish: "aimless", groupgerman: "Mangel an Bedeutung", groupenglish: "Lack of Meaning", explanationgerman: "Ohne Ziele oder Richtung; treibt ziellos umher. Beispiel 1: Ein zielloser Mensch weiß nicht, was er im Leben erreichen möchte. Beispiel 2: Ein zielloses Leben ohne Perspektive.", explanationenglish: "Without goals or direction; drifts aimlessly. Example 1: An aimless person doesn't know what they want to achieve in life. Example 2: An aimless life without perspective.", client_id: client.id)
Card.create!(categorygerman: "methodisch", categoryenglish: "methodical", positive: 0, namegerman: "zu theoretisch", nameenglish: "too theoretical", groupgerman: "Praxisfremd", groupenglish: "Lack of Practicality", explanationgerman: "Zu sehr auf Theorie fokussiert und praxisfern; wenig Bezug zur Realität. Beispiel 1: Ein zu theoretischer Ansatz ohne praktische Anwendung. Beispiel 2: Ein zu theoretischer Vortrag ohne reale Beispiele.", explanationenglish: "Overly focused on theory and impractical; little connection to reality. Example 1: An overly theoretical approach without practical application. Example 2: An overly theoretical presentation without real-world examples.", client_id: client.id)
Card.create!(categorygerman: "persönlich", categoryenglish: "personal", positive: 0, namegerman: "ambiguitätsintolerant", nameenglish: "not ambiguity-tolerant", groupgerman: "Starrheit", groupenglish: "Rigidity", explanationgerman: "Kann Mehrdeutigkeit und Ungenauigkeit nicht ertragen; braucht klare und eindeutige Antworten. Beispiel 1: Ein Ambiguitätsintoleranter hasst unklare Arbeitsanweisungen. Beispiel 2: Ein Ambiguitätsintoleranter mag keine Rätsel.", explanationenglish: "Cannot tolerate ambiguity and vagueness; needs clear and unambiguous answers. Example 1: A person intolerant of ambiguity hates unclear work instructions. Example 2: A person intolerant of ambiguity dislikes puzzles.", client_id: client.id)
Card.create!(categorygerman: "persönlich", categoryenglish: "personal", positive: 0, namegerman: "fremdmotiviert", nameenglish: "extrinsically motivated", groupgerman: "Mangel an Engagement", groupenglish: "Lack of Engagement", explanationgerman: "Motiviert durch äußere Faktoren, Belohnungen oder Druck; wenig intrinsische Motivation. Beispiel 1: Ein fremdmotivierter Schüler lernt nur, um gute Noten zu bekommen. Beispiel 2: Ein fremdmotivierter Mitarbeiter arbeitet nur, um seinen Job zu behalten.", explanationenglish: "Motivated by external factors, rewards, or pressure; little intrinsic motivation. Example 1: An extrinsically motivated student only studies to get good grades. Example 2: An extrinsically motivated employee only works to keep their job.", client_id: client.id)
Card.create!(categorygerman: "persönlich", categoryenglish: "personal", positive: 0, namegerman: "nicht selbstironisch", nameenglish: "not self-ironic", groupgerman: "Kontrollprobleme", groupenglish: "Control Issues", explanationgerman: "Nimmt sich selbst nicht auf die Schippe; fehlt der Humor, über eigene Schwächen zu lachen. Beispiel 1: Ein nicht selbstironischer Mensch reagiert auf Kritik sehr empfindlich. Beispiel 2: Ein nicht selbstironischer Mensch kann über seine Fehler nicht lachen.", explanationenglish: "Does not make fun of themselves; lacks the humor to laugh at their own weaknesses. Example 1: A person who is not self-ironic reacts very sensitively to criticism. Example 2: A person who is not self-ironic cannot laugh at their own mistakes.", client_id: client.id)
Card.create!(categorygerman: "persönlich", categoryenglish: "personal", positive: 0, namegerman: "sich selbst begrenzen", nameenglish: "limiting yourself", groupgerman: "Mangel an Bedeutung", groupenglish: "Lack of Meaning", explanationgerman: "Schränkt sich selbst ein, nutzt nicht sein volles Potential; traut sich nicht, über seine Grenzen hinauszugehen. Beispiel 1: Eine Person, die sich selbst begrenzt, traut sich nicht, einen neuen Job anzunehmen. Beispiel 2: Eine Person, die sich selbst begrenzt, entwickelt ihre Talente nicht.", explanationenglish: "Restricting oneself, not using one's full potential; not daring to go beyond one's limits. Example 1: A person who limits themselves does not dare to accept a new job. Example 2: A person who limits themselves does not develop their talents.", client_id: client.id)
Card.create!(categorygerman: "persönlich", categoryenglish: "personal", positive: 0, namegerman: "sinnsuchend", nameenglish: "in search of meaning", groupgerman: "Mangel an Bedeutung", groupenglish: "Lack of Meaning", explanationgerman: "Auf der Suche nach Sinn und Bedeutung im Leben; fragt nach dem Warum?. Beispiel 1: Ein sinnsuchender Mensch engagiert sich in sozialen Projekten. Beispiel 2: Ein sinnsuchender Mensch sucht nach spirituellen Antworten.", explanationenglish: "Seeking meaning and purpose in life; questions the why?. Example 1: A person searching for meaning gets involved in social projects. Example 2: A person searching for meaning seeks spiritual answers.", client_id: client.id)
Card.create!(categorygerman: "persönlich", categoryenglish: "personal", positive: 0, namegerman: "teilnahmslos", nameenglish: "apathetic", groupgerman: "Mangel an Engagement", groupenglish: "Lack of Engagement", explanationgerman: "Gleichgültig und uninteressiert am Schicksal anderer; zeigt keine Empathie. Beispiel 1: Ein teilnahmsloser Beobachter reagiert nicht auf das Leid anderer. Beispiel 2: Ein teilnahmsloser Zuschauer schaut sich ein Drama ohne Emotionen an.", explanationenglish: "Indifferent and uninterested in the fate of others; shows no empathy. Example 1: An apathetic observer doesn't react to the suffering of others. Example 2: An apathetic viewer watches a drama without emotion.", client_id: client.id)
Card.create!(categorygerman: "persönlich", categoryenglish: "personal", positive: 0, namegerman: "übermütig", nameenglish: "high-spirited", groupgerman: "Impulsivität", groupenglish: "Impulsivity", explanationgerman: "Überheblich, arrogant und eingebildet. Beispiel 1: Ein übermütiger Mensch glaubt, immer Recht zu haben. Beispiel 2: Ein übermütiger Schüler prahlt mit seinen Leistungen.", explanationenglish: "Arrogant, conceited, and self-important. Example 1: A high-spirited person believes they are always right. Example 2: A high-spirited student boasts about their achievements.", client_id: client.id)
Card.create!(categorygerman: "persönlich", categoryenglish: "personal", positive: 0, namegerman: "undiszipliniert", nameenglish: "undisciplined", groupgerman: "Impulsivität", groupenglish: "Impulsivity", explanationgerman: "Unordentlich, unorganisiert und nicht regelkonform. Beispiel 1: Ein undisziplinierter Schüler kommt oft zu spät zum Unterricht. Beispiel 2: Ein undisziplinierter Mitarbeiter erledigt seine Aufgaben nicht pünktlich.", explanationenglish: "Untidy, disorganized, and not rule-abiding. Example 1: An undisciplined student is often late for class. Example 2: An undisciplined employee does not complete their tasks on time.", client_id: client.id)
Card.create!(categorygerman: "persönlich", categoryenglish: "personal", positive: 0, namegerman: "unreflektiert", nameenglish: "without reflection", groupgerman: "Mangel an Bedeutung", groupenglish: "Lack of Meaning", explanationgerman: "Ohne Selbstreflexion; denkt nicht über sein Handeln und seine Konsequenzen nach. Beispiel 1: Ein unreflektierter Mensch handelt impulsiv, ohne die Folgen zu bedenken. Beispiel 2: Ein unreflektierter Kommentar ohne Hintergedanken.", explanationenglish: "Without self-reflection; does not think about their actions and their consequences. Example 1: An unreflective person acts impulsively without considering the consequences. Example 2: An unreflective comment without thinking.", client_id: client.id)
Card.create!(categorygerman: "persönlich", categoryenglish: "personal", positive: 0, namegerman: "unzuverlässig", nameenglish: "unreliable", groupgerman: "Vertrauensprobleme", groupenglish: "Trust Issues", explanationgerman: "Nicht vertrauenswürdig; hält Versprechen und Termine nicht ein. Beispiel 1: Ein unzuverlässiger Mitarbeiter kommt oft zu spät zur Arbeit. Beispiel 2: Ein unzuverlässiger Freund vergisst Verabredungen.", explanationenglish: "Untrustworthy; does not keep promises or meet deadlines. Example 1: An unreliable employee is often late for work. Example 2: An unreliable friend forgets appointments.", client_id: client.id)
Card.create!(categorygerman: "sozial", categoryenglish: "social", positive: 0, namegerman: "egoistisch", nameenglish: "selfish", groupgerman: "Starrheit", groupenglish: "Rigidity", explanationgerman: "Selbstbezogen und eigennützig; denkt nur an den eigenen Vorteil. Beispiel 1: Ein egoistischer Mensch teilt sein Essen nicht mit anderen. Beispiel 2: Ein egoistischer Mitarbeiter nimmt sich alle Erfolge selbst.", explanationenglish: "Self-centered and self-serving; only thinks about their own advantage. Example 1: A selfish person doesn't share their food with others. Example 2: A selfish employee takes all the credit for themselves.", client_id: client.id)
Card.create!(categorygerman: "sozial", categoryenglish: "social", positive: 0, namegerman: "intolerant", nameenglish: "intolerant", groupgerman: "Fairnessprobleme", groupenglish: "Fairness Issues", explanationgerman: "Unnachgiebig und ablehnend gegenüber anderen Meinungen und Lebensweisen. Beispiel 1: Ein intoleranter Mensch verachtet andere Kulturen. Beispiel 2: Ein intoleranter Chef duldet keine Kritik.", explanationenglish: "Inflexible and rejecting of other opinions and lifestyles. Example 1: An intolerant person despises other cultures. Example 2: An intolerant boss does not tolerate any criticism.", client_id: client.id)
Card.create!(categorygerman: "sozial", categoryenglish: "social", positive: 0, namegerman: "kaltherzig", nameenglish: "cold-hearted", groupgerman: "Mangel an Mitgefühl", groupenglish: "Lack of Compassion", explanationgerman: "Kalt, gefühlskalt und unmitleidig; zeigt wenig Empathie. Beispiel 1: Ein kaltherziger Mensch reagiert gleichgültig auf das Leid anderer. Beispiel 2: Ein kaltherziger Chef entlässt einen Mitarbeiter ohne Mitgefühl.", explanationenglish: "Cold, unfeeling, and unsympathetic; shows little empathy. Example 1: A cold-hearted person reacts indifferently to the suffering of others. Example 2: A cold-hearted boss fires an employee without compassion.", client_id: client.id)
Card.create!(categorygerman: "sozial", categoryenglish: "social", positive: 0, namegerman: "kontaktscheu", nameenglish: "reserved", groupgerman: "Vertrauensprobleme", groupenglish: "Trust Issues", explanationgerman: "Scheu vor sozialen Kontakten; zieht sich gerne zurück. Beispiel 1: Ein kontaktscheuer Mensch meidet Partys und große Veranstaltungen. Beispiel 2: Ein kontaktscheuer Schüler spricht nicht gerne mit seinen Mitschülern.", explanationenglish: "Shy and avoids social contact; prefers to withdraw. Example 1: A reserved person avoids parties and large events. Example 2: A reserved student doesn't like to talk to their classmates.", client_id: client.id)
Card.create!(categorygerman: "sozial", categoryenglish: "social", positive: 0, namegerman: "misstrauisch", nameenglish: "suspicious", groupgerman: "Vertrauensprobleme", groupenglish: "Trust Issues", explanationgerman: "Misstrauisch und skeptisch gegenüber anderen; glaubt eher an das Schlechte als an das Gute. Beispiel 1: Ein misstrauischer Mensch glaubt, dass alle Menschen egoistisch sind. Beispiel 2: Ein misstrauischer Mitarbeiter kontrolliert alles genau.", explanationenglish: "Mistrustful and skeptical of others; believes more in the bad than in the good. Example 1: A suspicious person believes that all people are selfish. Example 2: A suspicious employee carefully monitors everything.", client_id: client.id)
Card.create!(categorygerman: "sozial", categoryenglish: "social", positive: 0, namegerman: "nicht einfühlsam", nameenglish: "insensitive", groupgerman: "Mangel an Mitgefühl", groupenglish: "Lack of Compassion", explanationgerman: "Unempathisch und verständnislos; kann die Gefühle anderer nicht nachvollziehen. Beispiel 1: Ein nicht einfühlsamer Mensch macht sich über die Probleme anderer lustig. Beispiel 2: Ein nicht einfühlsamer Chef versteht die Sorgen seiner Mitarbeiter nicht.", explanationenglish: "Unempathetic and unsympathetic; cannot understand the feelings of others. Example 1: An insensitive person makes fun of the problems of others. Example 2: An insensitive boss doesn't understand the worries of their employees.", client_id: client.id)
Card.create!(categorygerman: "sozial", categoryenglish: "social", positive: 0, namegerman: "nicht unterstützend", nameenglish: "unsupportive", groupgerman: "Fairnessprobleme", groupenglish: "Fairness Issues", explanationgerman: "Bietet keine Hilfe oder Unterstützung an; lässt andere im Stich. Beispiel 1: Ein nicht unterstützender Freund hilft seinem Freund nicht in Not. Beispiel 2: Ein nicht unterstützender Partner hilft seinem Partner nicht bei seinen Zielen.", explanationenglish: "Does not offer help or support; lets others down. Example 1: An unsupportive friend doesn't help their friend in need. Example 2: An unsupportive partner doesn't help their partner achieve their goals.", client_id: client.id)
Card.create!(categorygerman: "sozial", categoryenglish: "social", positive: 0, namegerman: "respektlos", nameenglish: "disrespectful", groupgerman: "Fairnessprobleme", groupenglish: "Fairness Issues", explanationgerman: "Behandelt andere ohne Respekt und Wertschätzung; ist unhöflich und herablassend. Beispiel 1: Ein respektloser Schüler beschimpft seinen Lehrer. Beispiel 2: Ein respektloser Mitarbeiter beleidigt seine Kollegen.", explanationenglish: "Treats others without respect or appreciation; is rude and condescending. Example 1: A disrespectful student insults their teacher. Example 2: A disrespectful employee insults their colleagues.", client_id: client.id)
Card.create!(categorygerman: "sozial", categoryenglish: "social", positive: 0, namegerman: "rücksichtslos", nameenglish: "inconsiderate", groupgerman: "Mangel an Mitgefühl", groupenglish: "Lack of Compassion", explanationgerman: "Berücksichtigt nicht die Bedürfnisse und Gefühle anderer; handelt egoistisch und rücksichtslos. Beispiel 1: Ein rücksichtsloser Autofahrer parkt sein Auto auf dem Gehweg. Beispiel 2: Ein rücksichtsloser Mensch spricht andere schlecht über andere.", explanationenglish: "Does not consider the needs and feelings of others; acts selfishly and thoughtlessly. Example 1: An inconsiderate driver parks their car on the sidewalk. Example 2: An inconsiderate person talks badly about others.", client_id: client.id)
Card.create!(categorygerman: "sozial", categoryenglish: "social", positive: 0, namegerman: "ungerecht", nameenglish: "unfair", groupgerman: "Mangel an Mitgefühl", groupenglish: "Lack of Compassion", explanationgerman: "Unfair, parteiisch und ungleich; handelt nicht nach Gerechtigkeitsprinzipien. Beispiel 1: Eine ungerechte Verteilung von Ressourcen. Beispiel 2: Ein ungerechter Richter fällt ein voreingenommenes Urteil.", explanationenglish: "Unjust, biased, and unequal; does not act according to principles of justice. Example 1: An unfair distribution of resources. Example 2: An unfair judge makes a prejudiced judgment.", client_id: client.id)

# --------------------------------------------

# terminal message: Seeding completed
puts "Seeding completed"
